In [5]:
import pandas as pd
import numpy as np

In [2]:
pd.isna('dog')

False

In [3]:
pd.isna(pd.NA)

True

In [6]:
pd.isna(np.nan)

True

In [7]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])

In [8]:
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [9]:
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

In [10]:
index = pd.DatetimeIndex(["2017-07-05", "2017-07-06", None,
                          "2017-07-08"])

In [11]:
index

DatetimeIndex(['2017-07-05', '2017-07-06', 'NaT', '2017-07-08'], dtype='datetime64[ns]', freq=None)

In [12]:
pd.isna(index)

array([False, False,  True, False])

In [13]:
df = pd.DataFrame([['ant', 'bee', 'cat'], ['dog', None, 'fly']])

In [14]:
df

0     1    2
0  ant   bee  cat
1  dog  None  fly

In [15]:
pd.isna(df)

0      1      2
0  False  False  False
1  False   True  False

In [16]:
pd.isna(df[1])

0    False
1     True
Name: 1, dtype: bool